### ISSUE TITLE
CANBUS pins must be GPIO4 & GPIO5?

### ISSUE THREAD

**Issue by ghhsyy** [ThomasBarth/ESP32-CAN-Driver#11]
Good job!!! Thanks for sharing this dirver. I want use other pins for CAN, but I'm not sure it can work. I have test that GPIO4 and GPIO5 works well. 
good job!!!! Does it work when I use other pins besides GPIO4 & GPIO5?

**Comment by ghhsyy** [comment]
Is there any document about CANBUS of ESP32?

**Comment by ThomasBarth** [comment]
CAN also works on other pins.
The OLIMEX ESP32-EVB Board e.g. uses Pin 5 and 35.

As far as I know, there is no real documentation for CAN on the ESP32, I build the driver on the SJA100 specification.
