### ISSUE TITLE
Sending (writing) few frames in one go

### ISSUE THREAD

**Issue by martiinezz** [ThomasBarth/ESP32-CAN-Driver#17]
Hi, I have tried to send few frames (one after another different payload/ID each) and it seems only first one makes it to the canbus after calling CAN_write_frame on each set of data (confirmed by another device listening only). Any hints how to do it properly?

**Comment by sfowlr** [comment]
This driver currently doesn't block and wait until a transmit is completed before trying to send another, which may be the source of your issues. There's a fork that attempts to fix this issue at https://github.com/nayarsystems/ESP32-CAN-Driver/ - give that a try and see if it helps. I'd love to see these modifications pulled upstream into this repo, but nobody has put in a PR for it yet.

**Comment by martiinezz** [comment]
I have found well working library here: https://github.com/collin80
