### ISSUE TITLE
My can intr doesn't work

### ISSUE THREAD

**Issue by zhaochengwei** [ThomasBarth/ESP32-CAN-Driver#18]
![image](https://user-images.githubusercontent.com/13081827/41143970-d5308f38-6b2d-11e8-80a8-87f5b89101a4.png)
HOW can I make it work?
Need i open other interupt?

**Comment by 404ClickBait** [comment]
An interrupt is not something that is "opened".  An interrupt is an event.  An interrupt service routine is a bit of code that executes in response to the event.  First the interrupt service controller must be configured to execute your ISR in response to the interrupt event.

Are you sure the interrupt should be firing?  How are you triggering it?
