### ISSUE TITLE
Transceiver

### ISSUE THREAD

**Issue by rakhmaevao** [ThomasBarth/ESP32-CAN-Driver#23]
why does not it work with the ADM3053 transceiver?
How does the transponder selection affect?

**Comment by collin80** [comment]
I see no reason it wouldn't work. Were you sure to power the chip with 5v but put 3.3v on Vio?

**Comment by rakhmaevao** [comment]
yes.
I use 2 library:
thomas and https://github.com/sandeepmistry/arduino-CAN
Vcc 5 V
Vio +3,3 V

**Comment by rakhmaevao** [comment]
It also works with the ADM3053 driver.
the error in the scheme was.
