### ISSUE TITLE
This driver vs ESPIDF

### ISSUE THREAD

**Issue by mickeyl** [ThomasBarth/ESP32-CAN-Driver#30]
I wonder what‘s the benefit of using this driver instead of the builtin TWAI driver in ESP-IDF. Is it faster or more reliable?

**Comment by krsche** [comment]
If I remember correctly then this was here before there was a (good) builtin driver. I'ts a long time ago I used it, so no idea if there are other diffs or reasons

**Comment by mickeyl** [comment]
Alright, thanks.

**Comment by dpharris** [comment]
I also wonder.  The built-in driver requires RTOS, and so more over-head?
Has anyone compared them?

David
