### ISSUE TITLE
Maybe it does not work

### ISSUE THREAD

**Issue by wangsuyu** [ThomasBarth/ESP32-CAN-Driver#4]
Hi,ThomasBarth.
    Now I am workingt on ESP32-IDF，and I want to make can works.Thanks for espressif engineers recommand you to me.But it does not work when I make a test on your code.So,I want to make sure that have you ever test?If works,can you commit an example for me?Thank you very much.
Best Regards
Suyu Wang

**Comment by santanapablo1975** [comment]
Hi

For a example take a look here

https://github.com/ESP32DE/ESP32-CAN-Driver/releases/tag/0.1

I made the test and it works very good!!!

Thanks Thomas! and Rudi!

Regards

Juan

**Comment by wangsuyu** [comment]
Hi,Juan
Thanks for your response.Due to weekday,I do not have an esp32 to vertify.So,I spent several hours to read you code and leart a lot from yours.Thank you very much!
Thanks Thomas! ,Rudi! and @santanapablo1975 
Best Regards
Suyu Wang

**Comment by wangsuyu** [comment]
Hi,juan
Sorry for a late update,I made some mistakes,so I just work your example well.
Thanks everyone!
Best Regards
Suyu Wang
