### ISSUE TITLE
component.mk linker issue

### ISSUE THREAD

**Issue by Beck-Sisyphus** [ThomasBarth/ESP32-CAN-Driver#5]
In the component.mk file contains

COMPONENT_ADD_INCLUDEDIRS 	:= / components/CAN/include
COMPONENT_SRCDIRS			:= / components/CAN components/CAN/cfg

If I keep the := / directory I got this error:

/ESP32-CAN-Driver/main///main.c:102:1: fatal error: opening dependency file /main.d: Permission denied

If I remove the := / directory I got a lot more dependency issues:

ESP32-CAN-Driver/main/components/CAN/include/can_regdef.h:34:1: error: expected identifier or '(' before ')' token
 )

May I know how to solve it?

**Comment by wangsuyu** [comment]
Hi,you can  change  '/' to '.' to solve the problem
