### ISSUE TITLE
Demo missing

### ISSUE THREAD

**Issue by pauloacmartinez** [ThomasBarth/ESP32-CAN-Driver#8]
Hi! I found a demo of the driver in your website, but it doesn't work with the current version of esp-idf, nor this updated version has a demo of the driver.

**Comment by ghhsyy** [comment]
You can find demo from author's website.

**Comment by ghhsyy** [comment]
You may not define CAN_cfg.

**Comment by enex** [comment]
The demo does not work with current version of esp-idf it would be nice to have a recent version because i can't get anything can controller related to work.
